### ISSUE TITLE
etcd.EtcdKeyNotFound: Key not found : /torchelastic/p2p/run_c63361db-da0b-40ca-90a6-a59be99e2a0b/rdzv/next_strategy

### ISSUE THREAD

**Issue by laochonlam** [JF-D/Parcae#1]
Hi, thanks for releasing Parcae. Great work! I am running Parcae but am currently encountering some errors. 

When I run `sh replay_trace_run.sh 32 traces/gpt-1.5b/trace_hh_55_65.txt` with my own machines and settings, the process gets stuck at the following error every rendezvous:

```
  File "/usr/local/lib/python3.8/dist-packages/etcd/client.py", line 740, in get
    return self.read(key)
  File "/usr/local/lib/python3.8/dist-packages/etcd/client.py", line 595, in read
    response = self.api_execute(
  File "/usr/local/lib/python3.8/dist-packages/etcd/client.py", line 907, in wrapper
    return self._handle_server_response(response)
  File "/usr/local/lib/python3.8/dist-packages/etcd/client.py", line 987, in _handle_server_response
    etcd.EtcdError.handle(r)
  File "/usr/local/lib/python3.8/dist-packages/etcd/__init__.py", line 306, in handle
    raise exc(msg, payload)
etcd.EtcdKeyNotFound: Key not found : /torchelastic/p2p/run_c63361db-da0b-40ca-90a6-a59be99e2a0b/rdzv/next_strategy
INFO 2024-06-12 12:55:46,077 Node x08j11224.cloud.sqa.na131 Attempting to join next rendezvous
```

Additionally, I cannot find any part of the code that writes rdzv/next_strategy to the etcd.

Do you have any clues or suggestions on how to resolve this error?

Thank you!
Lam

**Comment by JF-D** [comment]
The `next_strategy` is issued at [here](https://github.com/JF-D/Parcae/blob/main/aws/replay_trace.py#L371) and will be used at [etcd](https://github.com/JF-D/Parcae/blob/main/project_pactum/rendezvous/etcd.py#L1394) and [engine](https://github.com/JF-D/Parcae/blob/main/deepspeed/runtime/pipe/engine.py#L2020). Hope this can help you find the bug.

**Comment by laochonlam** [comment]
Thanks - I found out that the bug is due to the incorrect environment being passed to my Docker.

Lam
